// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNY6w_gKFQzC7NL-bXlPDAho-cQMBWZD8',
    appId: '1:1074340533408:web:2cba7e66b55c34ac1c65c5',
    messagingSenderId: '1074340533408',
    projectId: 'qalam-4375d',
    authDomain: 'qalam-4375d.firebaseapp.com',
    databaseURL: 'https://qalam-4375d-default-rtdb.firebaseio.com',
    storageBucket: 'qalam-4375d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi2v8vHX00aWudsIpKPDr9amSjqIXAB7w',
    appId: '1:1074340533408:android:5e65b7ef4cdb1c171c65c5',
    messagingSenderId: '1074340533408',
    projectId: 'qalam-4375d',
    databaseURL: 'https://qalam-4375d-default-rtdb.firebaseio.com',
    storageBucket: 'qalam-4375d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqViqcFnDZE8lcZ7rU3dDmosstU6jAG0Q',
    appId: '1:1074340533408:ios:a60c468bcb131da61c65c5',
    messagingSenderId: '1074340533408',
    projectId: 'qalam-4375d',
    databaseURL: 'https://qalam-4375d-default-rtdb.firebaseio.com',
    storageBucket: 'qalam-4375d.firebasestorage.app',
    iosBundleId: 'com.example.hatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqViqcFnDZE8lcZ7rU3dDmosstU6jAG0Q',
    appId: '1:1074340533408:ios:a60c468bcb131da61c65c5',
    messagingSenderId: '1074340533408',
    projectId: 'qalam-4375d',
    databaseURL: 'https://qalam-4375d-default-rtdb.firebaseio.com',
    storageBucket: 'qalam-4375d.firebasestorage.app',
    iosBundleId: 'com.example.hatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNY6w_gKFQzC7NL-bXlPDAho-cQMBWZD8',
    appId: '1:1074340533408:web:847d9c949c36767b1c65c5',
    messagingSenderId: '1074340533408',
    projectId: 'qalam-4375d',
    authDomain: 'qalam-4375d.firebaseapp.com',
    databaseURL: 'https://qalam-4375d-default-rtdb.firebaseio.com',
    storageBucket: 'qalam-4375d.firebasestorage.app',
  );
}
